// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "710db436-249d-4907-9672-720f82406fc0");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1672651476);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1672651469);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{3c9e7c05-bc21-473c-b3d9-595feca02813}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1672651466);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b4881a7c-0d59-4dd0-89f2-fe2497d22a59}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1672651468);
user_pref("browser.search.region", "FR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1672651472");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220922094448");
user_pref("browser.startup.homepage_override.mstone", "102.3.0");
user_pref("browser.startup.lastColdStartupCheck", 1672651470);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1672651471686");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "102.3.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "FR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "2b9482091e45423fb133937ea4030b5f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1672651469);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220922094448");
user_pref("extensions.lastAppVersion", "102.3.0");
user_pref("extensions.lastPlatformVersion", "102.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"2d2eea33-3662-4269-b737-a439f07620fa\",\"formautofill@mozilla.org\":\"5e3f29fd-f167-451d-a475-394be150cd05\",\"pictureinpicture@mozilla.org\":\"108e97e5-b327-426f-bec9-7ffe563193b8\",\"screenshots@mozilla.org\":\"7c9b8343-3770-4d71-b537-0ec3f5a71d5c\",\"webcompat-reporter@mozilla.org\":\"1aa99d1e-e552-4005-a510-a0e0ae5f77c9\",\"webcompat@mozilla.org\":\"401cba4d-6e9d-46a2-b6a4-19ecc7584a3e\",\"default-theme@mozilla.org\":\"6269bec6-6bee-42f2-ada7-b9787a45ad40\",\"addons-search-detection@mozilla.com\":\"566ee918-47e3-4a4f-8e8c-30c0068780bf\",\"google@search.mozilla.org\":\"b33551b7-6927-48f6-a759-a97bf6ed6c42\",\"wikipedia@search.mozilla.org\":\"8baafb3b-7995-458e-9d98-cc6de187820c\",\"bing@search.mozilla.org\":\"bef918b0-e6c2-4587-ae65-7cde4bd078ba\",\"amazon@search.mozilla.org\":\"9cbaf743-7d35-486c-9357-f62064562ac9\",\"ddg@search.mozilla.org\":\"3fbd08c3-291b-4049-aedb-c999d0668908\",\"ebay@search.mozilla.org\":\"92040385-805d-4a97-81ba-00c3398861c1\",\"qwant@search.mozilla.org\":\"b72e928e-caf7-4f47-9a4b-b6417d392b68\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1672651475);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a36a663f-f75b-4688-a150-2a12d9dce4e7");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1672651460);
user_pref("toolkit.telemetry.cachedClientID", "249a6ae8-1ca3-49d2-a008-795e7a0cf8bb");
user_pref("toolkit.telemetry.previousBuildID", "20220922094448");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
